#############################################################################
# Makefile for building: hello
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  hello.pro
# Template: app
# Command: /home/sergey/Qt/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile hello.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../Qt/5.3/gcc_64/mkspecs/linux-g++ -I. -I../Qt/5.3/gcc_64/include -I../Qt/5.3/gcc_64/include/QtWidgets -I../Qt/5.3/gcc_64/include/QtNetwork -I../Qt/5.3/gcc_64/include/QtGui -I../Qt/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/sergey/Qt/5.3/gcc_64 -Wl,-rpath,/home/sergey/Qt/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/sergey/Qt/5.3/gcc_64/lib -lQt5Widgets -lQt5Network -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/sergey/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		goprocontroller.cpp moc_mainwindow.cpp \
		moc_goprocontroller.cpp
OBJECTS       = main.o \
		mainwindow.o \
		goprocontroller.o \
		moc_mainwindow.o \
		moc_goprocontroller.o
DIST          = ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.3/gcc_64/mkspecs/features/uic.prf \
		../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		hello.pro main.cpp \
		mainwindow.cpp \
		goprocontroller.cpp
QMAKE_TARGET  = hello
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = hello


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: hello.pro ../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		../Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		../Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		../Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt/5.3/gcc_64/mkspecs/features/uic.prf \
		../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		../Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		../Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		hello.pro \
		/home/sergey/Qt/5.3/gcc_64/lib/libQt5Widgets.prl \
		/home/sergey/Qt/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/sergey/Qt/5.3/gcc_64/lib/libQt5Core.prl \
		/home/sergey/Qt/5.3/gcc_64/lib/libQt5Network.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile hello.pro
../Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
../Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/linux.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
../Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
../Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
../Qt/5.3/gcc_64/mkspecs/qconfig.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
../Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
../Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
../Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
../Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
../Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
../Qt/5.3/gcc_64/mkspecs/features/qt.prf:
../Qt/5.3/gcc_64/mkspecs/features/resources.prf:
../Qt/5.3/gcc_64/mkspecs/features/moc.prf:
../Qt/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt/5.3/gcc_64/mkspecs/features/uic.prf:
../Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf:
../Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
../Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
../Qt/5.3/gcc_64/mkspecs/features/lex.prf:
hello.pro:
/home/sergey/Qt/5.3/gcc_64/lib/libQt5Widgets.prl:
/home/sergey/Qt/5.3/gcc_64/lib/libQt5Gui.prl:
/home/sergey/Qt/5.3/gcc_64/lib/libQt5Core.prl:
/home/sergey/Qt/5.3/gcc_64/lib/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile hello.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/hello1.0.0 || mkdir -p .tmp/hello1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/hello1.0.0/ && $(COPY_FILE) --parents mainwindow.h goprocontroller.h .tmp/hello1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp goprocontroller.cpp .tmp/hello1.0.0/ && (cd `dirname .tmp/hello1.0.0` && $(TAR) hello1.0.0.tar hello1.0.0 && $(COMPRESS) hello1.0.0.tar) && $(MOVE) `dirname .tmp/hello1.0.0`/hello1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hello1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_goprocontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_goprocontroller.cpp
moc_mainwindow.cpp: ../Qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../Qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../Qt/5.3/gcc_64/include/QtCore/qflags.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qstring.h \
		../Qt/5.3/gcc_64/include/QtCore/qchar.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/5.3/gcc_64/include/QtCore/qlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qrect.h \
		../Qt/5.3/gcc_64/include/QtCore/qsize.h \
		../Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qpair.h \
		../Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../Qt/5.3/gcc_64/include/QtCore/qvector.h \
		../Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../Qt/5.3/gcc_64/include/QtGui/qregion.h \
		../Qt/5.3/gcc_64/include/QtCore/qline.h \
		../Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../Qt/5.3/gcc_64/include/QtGui/qimage.h \
		../Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qhash.h \
		../Qt/5.3/gcc_64/include/QtGui/qfont.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../Qt/5.3/gcc_64/include/QtGui/qevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../Qt/5.3/gcc_64/include/QtCore/qmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../Qt/5.3/gcc_64/include/QtCore/qset.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.3/gcc_64/include/QtCore/qurl.h \
		../Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../Qt/5.3/gcc_64/include/QtCore/qfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qicon.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../Qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		goprocontroller.h \
		../Qt/5.3/gcc_64/include/QtCore/QString \
		../Qt/5.3/gcc_64/include/QtCore/QObject \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatetime.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qssl.h \
		../Qt/5.3/gcc_64/include/QtCore/QFlags \
		../Qt/5.3/gcc_64/include/QtCore/QUrl \
		mainwindow.h
	/home/sergey/Qt/5.3/gcc_64/bin/moc $(DEFINES) -I/home/sergey/Qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/sergey/hello -I/home/sergey/Qt/5.3/gcc_64/include -I/home/sergey/Qt/5.3/gcc_64/include/QtWidgets -I/home/sergey/Qt/5.3/gcc_64/include/QtNetwork -I/home/sergey/Qt/5.3/gcc_64/include/QtGui -I/home/sergey/Qt/5.3/gcc_64/include/QtCore mainwindow.h -o moc_mainwindow.cpp

moc_goprocontroller.cpp: ../Qt/5.3/gcc_64/include/QtCore/QString \
		../Qt/5.3/gcc_64/include/QtCore/qstring.h \
		../Qt/5.3/gcc_64/include/QtCore/qchar.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../Qt/5.3/gcc_64/include/QtCore/qflags.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/5.3/gcc_64/include/QtCore/QObject \
		../Qt/5.3/gcc_64/include/QtCore/qobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../Qt/5.3/gcc_64/include/QtCore/qhash.h \
		../Qt/5.3/gcc_64/include/QtCore/qpair.h \
		../Qt/5.3/gcc_64/include/QtCore/qmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qvector.h \
		../Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../Qt/5.3/gcc_64/include/QtCore/qset.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatetime.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qssl.h \
		../Qt/5.3/gcc_64/include/QtCore/QFlags \
		../Qt/5.3/gcc_64/include/QtCore/QUrl \
		../Qt/5.3/gcc_64/include/QtCore/qurl.h \
		../Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		goprocontroller.h
	/home/sergey/Qt/5.3/gcc_64/bin/moc $(DEFINES) -I/home/sergey/Qt/5.3/gcc_64/mkspecs/linux-g++ -I/home/sergey/hello -I/home/sergey/Qt/5.3/gcc_64/include -I/home/sergey/Qt/5.3/gcc_64/include/QtWidgets -I/home/sergey/Qt/5.3/gcc_64/include/QtNetwork -I/home/sergey/Qt/5.3/gcc_64/include/QtGui -I/home/sergey/Qt/5.3/gcc_64/include/QtCore goprocontroller.h -o moc_goprocontroller.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../Qt/5.3/gcc_64/include/QtCore/QDebug \
		../Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../Qt/5.3/gcc_64/include/QtCore/qflags.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../Qt/5.3/gcc_64/include/QtCore/qhash.h \
		../Qt/5.3/gcc_64/include/QtCore/qchar.h \
		../Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../Qt/5.3/gcc_64/include/QtCore/qpair.h \
		../Qt/5.3/gcc_64/include/QtCore/qmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qstring.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../Qt/5.3/gcc_64/include/QtCore/qvector.h \
		../Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../Qt/5.3/gcc_64/include/QtCore/qset.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		mainwindow.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../Qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qrect.h \
		../Qt/5.3/gcc_64/include/QtCore/qsize.h \
		../Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../Qt/5.3/gcc_64/include/QtGui/qregion.h \
		../Qt/5.3/gcc_64/include/QtCore/qline.h \
		../Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../Qt/5.3/gcc_64/include/QtGui/qimage.h \
		../Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.3/gcc_64/include/QtGui/qfont.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../Qt/5.3/gcc_64/include/QtGui/qevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qurl.h \
		../Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../Qt/5.3/gcc_64/include/QtCore/qfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qicon.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../Qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		goprocontroller.h \
		../Qt/5.3/gcc_64/include/QtCore/QString \
		../Qt/5.3/gcc_64/include/QtCore/QObject \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatetime.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qssl.h \
		../Qt/5.3/gcc_64/include/QtCore/QFlags \
		../Qt/5.3/gcc_64/include/QtCore/QUrl \
		../Qt/5.3/gcc_64/include/QtWidgets/QApplication \
		../Qt/5.3/gcc_64/include/QtWidgets/qapplication.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qguiapplication.h \
		../Qt/5.3/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QMainWindow \
		../Qt/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../Qt/5.3/gcc_64/include/QtCore/qflags.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qstring.h \
		../Qt/5.3/gcc_64/include/QtCore/qchar.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/5.3/gcc_64/include/QtCore/qlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../Qt/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qrect.h \
		../Qt/5.3/gcc_64/include/QtCore/qsize.h \
		../Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../Qt/5.3/gcc_64/include/QtGui/qpalette.h \
		../Qt/5.3/gcc_64/include/QtGui/qcolor.h \
		../Qt/5.3/gcc_64/include/QtGui/qrgb.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qpair.h \
		../Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/5.3/gcc_64/include/QtGui/qbrush.h \
		../Qt/5.3/gcc_64/include/QtCore/qvector.h \
		../Qt/5.3/gcc_64/include/QtGui/qmatrix.h \
		../Qt/5.3/gcc_64/include/QtGui/qpolygon.h \
		../Qt/5.3/gcc_64/include/QtGui/qregion.h \
		../Qt/5.3/gcc_64/include/QtCore/qline.h \
		../Qt/5.3/gcc_64/include/QtGui/qtransform.h \
		../Qt/5.3/gcc_64/include/QtGui/qpainterpath.h \
		../Qt/5.3/gcc_64/include/QtGui/qimage.h \
		../Qt/5.3/gcc_64/include/QtGui/qpixmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qhash.h \
		../Qt/5.3/gcc_64/include/QtGui/qfont.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt/5.3/gcc_64/include/QtGui/qfontinfo.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt/5.3/gcc_64/include/QtGui/qcursor.h \
		../Qt/5.3/gcc_64/include/QtGui/qkeysequence.h \
		../Qt/5.3/gcc_64/include/QtGui/qevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../Qt/5.3/gcc_64/include/QtCore/qmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../Qt/5.3/gcc_64/include/QtCore/qset.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.3/gcc_64/include/QtCore/qurl.h \
		../Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../Qt/5.3/gcc_64/include/QtCore/qfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../Qt/5.3/gcc_64/include/QtGui/qvector2d.h \
		../Qt/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		../Qt/5.3/gcc_64/include/QtGui/qicon.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QPushButton \
		../Qt/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		../Qt/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		goprocontroller.h \
		../Qt/5.3/gcc_64/include/QtCore/QString \
		../Qt/5.3/gcc_64/include/QtCore/QObject \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatetime.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qssl.h \
		../Qt/5.3/gcc_64/include/QtCore/QFlags \
		../Qt/5.3/gcc_64/include/QtCore/QUrl \
		../Qt/5.3/gcc_64/include/QtCore/QCoreApplication \
		../Qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../Qt/5.3/gcc_64/include/QtWidgets/QTabWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

goprocontroller.o: goprocontroller.cpp goprocontroller.h \
		../Qt/5.3/gcc_64/include/QtCore/QString \
		../Qt/5.3/gcc_64/include/QtCore/qstring.h \
		../Qt/5.3/gcc_64/include/QtCore/qchar.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobal.h \
		../Qt/5.3/gcc_64/include/QtCore/qconfig.h \
		../Qt/5.3/gcc_64/include/QtCore/qfeatures.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qtypetraits.h \
		../Qt/5.3/gcc_64/include/QtCore/qsysinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qlogging.h \
		../Qt/5.3/gcc_64/include/QtCore/qflags.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		../Qt/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		../Qt/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt/5.3/gcc_64/include/QtCore/qmutex.h \
		../Qt/5.3/gcc_64/include/QtCore/qnumeric.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearray.h \
		../Qt/5.3/gcc_64/include/QtCore/qrefcount.h \
		../Qt/5.3/gcc_64/include/QtCore/qnamespace.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydata.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt/5.3/gcc_64/include/QtCore/QObject \
		../Qt/5.3/gcc_64/include/QtCore/qobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt/5.3/gcc_64/include/QtCore/qlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qalgorithms.h \
		../Qt/5.3/gcc_64/include/QtCore/qiterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qcoreevent.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetatype.h \
		../Qt/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt/5.3/gcc_64/include/QtCore/qisenum.h \
		../Qt/5.3/gcc_64/include/QtCore/qobject_impl.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkAccessManager \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkaccessmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QSslConfiguration \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslconfiguration.h \
		../Qt/5.3/gcc_64/include/QtCore/qshareddata.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslsocket.h \
		../Qt/5.3/gcc_64/include/QtCore/qregexp.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractsocket.h \
		../Qt/5.3/gcc_64/include/QtCore/qiodevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qdebug.h \
		../Qt/5.3/gcc_64/include/QtCore/qhash.h \
		../Qt/5.3/gcc_64/include/QtCore/qpair.h \
		../Qt/5.3/gcc_64/include/QtCore/qmap.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qlocale.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariant.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatastream.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qvector.h \
		../Qt/5.3/gcc_64/include/QtCore/qpoint.h \
		../Qt/5.3/gcc_64/include/QtCore/qset.h \
		../Qt/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslerror.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificate.h \
		../Qt/5.3/gcc_64/include/QtCore/qcryptographichash.h \
		../Qt/5.3/gcc_64/include/QtCore/qdatetime.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qssl.h \
		../Qt/5.3/gcc_64/include/QtCore/QFlags \
		../Qt/5.3/gcc_64/include/QtCore/QUrl \
		../Qt/5.3/gcc_64/include/QtCore/qurl.h \
		../Qt/5.3/gcc_64/include/QtCore/qurlquery.h \
		../Qt/5.3/gcc_64/include/QtCore/QCoreApplication \
		../Qt/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt/5.3/gcc_64/include/QtCore/qeventloop.h \
		../Qt/5.3/gcc_64/include/QtNetwork/QtNetwork \
		../Qt/5.3/gcc_64/include/QtNetwork/QtNetworkDepends \
		../Qt/5.3/gcc_64/include/QtCore/QtCore \
		../Qt/5.3/gcc_64/include/QtCore/QtCoreDepends \
		../Qt/5.3/gcc_64/include/QtCore/qabstractanimation.h \
		../Qt/5.3/gcc_64/include/QtCore/qanimationgroup.h \
		../Qt/5.3/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../Qt/5.3/gcc_64/include/QtCore/qpauseanimation.h \
		../Qt/5.3/gcc_64/include/QtCore/qpropertyanimation.h \
		../Qt/5.3/gcc_64/include/QtCore/qvariantanimation.h \
		../Qt/5.3/gcc_64/include/QtCore/qeasingcurve.h \
		../Qt/5.3/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextcodec.h \
		../Qt/5.3/gcc_64/include/QtCore/qendian.h \
		../Qt/5.3/gcc_64/include/QtCore/qlibraryinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qbuffer.h \
		../Qt/5.3/gcc_64/include/QtCore/qdir.h \
		../Qt/5.3/gcc_64/include/QtCore/qfileinfo.h \
		../Qt/5.3/gcc_64/include/QtCore/qfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qfiledevice.h \
		../Qt/5.3/gcc_64/include/QtCore/qdiriterator.h \
		../Qt/5.3/gcc_64/include/QtCore/qfileselector.h \
		../Qt/5.3/gcc_64/include/QtCore/QStringList \
		../Qt/5.3/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qlockfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qloggingcategory.h \
		../Qt/5.3/gcc_64/include/QtCore/qprocess.h \
		../Qt/5.3/gcc_64/include/QtCore/qresource.h \
		../Qt/5.3/gcc_64/include/QtCore/qsavefile.h \
		../Qt/5.3/gcc_64/include/QtCore/qsettings.h \
		../Qt/5.3/gcc_64/include/QtCore/qstandardpaths.h \
		../Qt/5.3/gcc_64/include/QtCore/qtemporarydir.h \
		../Qt/5.3/gcc_64/include/QtCore/QScopedPointer \
		../Qt/5.3/gcc_64/include/QtCore/qtemporaryfile.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstractitemmodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstractproxymodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qidentityproxymodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qitemselectionmodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qstringlistmodel.h \
		../Qt/5.3/gcc_64/include/QtCore/qjsonarray.h \
		../Qt/5.3/gcc_64/include/QtCore/qjsonvalue.h \
		../Qt/5.3/gcc_64/include/QtCore/qjsondocument.h \
		../Qt/5.3/gcc_64/include/QtCore/qjsonobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../Qt/5.3/gcc_64/include/QtCore/qbasictimer.h \
		../Qt/5.3/gcc_64/include/QtCore/qmath.h \
		../Qt/5.3/gcc_64/include/QtCore/qmetaobject.h \
		../Qt/5.3/gcc_64/include/QtCore/qmimedata.h \
		../Qt/5.3/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../Qt/5.3/gcc_64/include/QtCore/qpointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qsharedmemory.h \
		../Qt/5.3/gcc_64/include/QtCore/qsignalmapper.h \
		../Qt/5.3/gcc_64/include/QtCore/qsocketnotifier.h \
		../Qt/5.3/gcc_64/include/QtCore/qsystemsemaphore.h \
		../Qt/5.3/gcc_64/include/QtCore/qtimer.h \
		../Qt/5.3/gcc_64/include/QtCore/qtranslator.h \
		../Qt/5.3/gcc_64/include/QtCore/qwineventnotifier.h \
		../Qt/5.3/gcc_64/include/QtCore/qmimedatabase.h \
		../Qt/5.3/gcc_64/include/QtCore/qmimetype.h \
		../Qt/5.3/gcc_64/include/QtCore/qfactoryinterface.h \
		../Qt/5.3/gcc_64/include/QtCore/qlibrary.h \
		../Qt/5.3/gcc_64/include/QtCore/qplugin.h \
		../Qt/5.3/gcc_64/include/QtCore/qpluginloader.h \
		../Qt/5.3/gcc_64/include/QtCore/quuid.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstractstate.h \
		../Qt/5.3/gcc_64/include/QtCore/qabstracttransition.h \
		../Qt/5.3/gcc_64/include/QtCore/qeventtransition.h \
		../Qt/5.3/gcc_64/include/QtCore/qfinalstate.h \
		../Qt/5.3/gcc_64/include/QtCore/qhistorystate.h \
		../Qt/5.3/gcc_64/include/QtCore/qsignaltransition.h \
		../Qt/5.3/gcc_64/include/QtCore/qstate.h \
		../Qt/5.3/gcc_64/include/QtCore/qstatemachine.h \
		../Qt/5.3/gcc_64/include/QtCore/qexception.h \
		../Qt/5.3/gcc_64/include/QtCore/qfuture.h \
		../Qt/5.3/gcc_64/include/QtCore/qfutureinterface.h \
		../Qt/5.3/gcc_64/include/QtCore/qrunnable.h \
		../Qt/5.3/gcc_64/include/QtCore/qresultstore.h \
		../Qt/5.3/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../Qt/5.3/gcc_64/include/QtCore/qfuturewatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qreadwritelock.h \
		../Qt/5.3/gcc_64/include/QtCore/qsemaphore.h \
		../Qt/5.3/gcc_64/include/QtCore/qthread.h \
		../Qt/5.3/gcc_64/include/QtCore/qthreadpool.h \
		../Qt/5.3/gcc_64/include/QtCore/qthreadstorage.h \
		../Qt/5.3/gcc_64/include/QtCore/qwaitcondition.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydataops.h \
		../Qt/5.3/gcc_64/include/QtCore/qarraydatapointer.h \
		../Qt/5.3/gcc_64/include/QtCore/qbitarray.h \
		../Qt/5.3/gcc_64/include/QtCore/qbytearraymatcher.h \
		../Qt/5.3/gcc_64/include/QtCore/qcache.h \
		../Qt/5.3/gcc_64/include/QtCore/qcollator.h \
		../Qt/5.3/gcc_64/include/QtCore/qcommandlineoption.h \
		../Qt/5.3/gcc_64/include/QtCore/qcommandlineparser.h \
		../Qt/5.3/gcc_64/include/QtCore/qelapsedtimer.h \
		../Qt/5.3/gcc_64/include/QtCore/qline.h \
		../Qt/5.3/gcc_64/include/QtCore/qlinkedlist.h \
		../Qt/5.3/gcc_64/include/QtCore/qmargins.h \
		../Qt/5.3/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../Qt/5.3/gcc_64/include/QtCore/qqueue.h \
		../Qt/5.3/gcc_64/include/QtCore/qrect.h \
		../Qt/5.3/gcc_64/include/QtCore/qsize.h \
		../Qt/5.3/gcc_64/include/QtCore/qregularexpression.h \
		../Qt/5.3/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../Qt/5.3/gcc_64/include/QtCore/qstack.h \
		../Qt/5.3/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../Qt/5.3/gcc_64/include/QtCore/qtimeline.h \
		../Qt/5.3/gcc_64/include/QtCore/qtimezone.h \
		../Qt/5.3/gcc_64/include/QtCore/qxmlstream.h \
		../Qt/5.3/gcc_64/include/QtCore/qtcoreversion.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qabstractnetworkcache.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkrequest.h \
		../Qt/5.3/gcc_64/include/QtCore/QSharedDataPointer \
		../Qt/5.3/gcc_64/include/QtCore/QVariant \
		../Qt/5.3/gcc_64/include/QtNetwork/qhttpmultipart.h \
		../Qt/5.3/gcc_64/include/QtCore/QByteArray \
		../Qt/5.3/gcc_64/include/QtCore/QIODevice \
		../Qt/5.3/gcc_64/include/QtNetwork/QNetworkRequest \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkcookie.h \
		../Qt/5.3/gcc_64/include/QtCore/QList \
		../Qt/5.3/gcc_64/include/QtCore/QMetaType \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkcookiejar.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkdiskcache.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkreply.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkconfigmanager.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkconfiguration.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworksession.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkinterface.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qhostaddress.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qauthenticator.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qdnslookup.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qhostinfo.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qnetworkproxy.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qlocalserver.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qlocalsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtcpserver.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qudpsocket.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcertificateextension.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslcipher.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qsslkey.h \
		../Qt/5.3/gcc_64/include/QtNetwork/qtnetworkversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o goprocontroller.o goprocontroller.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_goprocontroller.o: moc_goprocontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_goprocontroller.o moc_goprocontroller.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

